all:
  children:
    control:
      hosts:
        127.0.0.1:
          ansible_connection: local

    localarch:
      hosts:
        work.angellus.wl.mort.is:
        server-2.wl.mort.is:
        pi-1.wl.mort.is:
        pi-2.wl.mort.is:
        pi-3.wl.mort.is:
        pi-4.wl.mort.is:
        pi-5.wl.mort.is:

    pi:
      hosts:
        pi-1.wl.mort.is:
        pi-2.wl.mort.is:
        pi-3.wl.mort.is:
        pi-4.wl.mort.is:
        pi-5.wl.mort.is:
      children:
        pirack:
        roomassistant:

    pirack:
      hosts:
        pi-1.wl.mort.is:
        pi-2.wl.mort.is:
        pi-3.wl.mort.is:
        pi-4.wl.mort.is:
      children:
        dns:

    dns:
      hosts:
        pi-1.wl.mort.is:
          ansible_host: 192.168.1.10
        pi-2.wl.mort.is:
          ansible_host: 192.168.1.12

    roomassistant:
      hosts:
        pi-5.wl.mort.is:

    download:
      hosts:
        fr.mort.is:

    vacuum:
      hosts:
        vacuum-1.wl.mort.is:
