install_pihole: true

# list of domains to whitelist for Pihole
pihole_whitelist:
  - collector.newrelic.com
  - adfoc.us

# Extra systemd services to enable
# Set to '[]' to skip
extra_systemd:
  - netdata.service

# dns hosts file
# set to null to skip
dns_hosts: 'user/mortis-configs/templates/hosts'

# extra arbitary system files to copy
# set to '[]' to not copy any
extra_system_files:
    - { src: user/mortis-configs/templates/netdata/.opt-out, dest: /etc/netdata/.opt-out-from-anonymous-statistics }
    - { src: user/mortis-configs/templates/netdata/apps_groups.conf, dest: /etc/netdata/apps_groups.conf }
    - { src: user/mortis-configs/templates/netdata/netdata.pi-1.conf, dest: /etc/netdata/netdata.conf }
    - { src: user/mortis-configs/templates/netdata/python.d.conf, dest: /etc/netdata/python.d.conf }
    - { src: user/mortis-configs/templates/sysctl.conf, dest: /etc/sysctl.d/90-extra-tuning.conf }
    - { src: user/mortis-configs/templates/netdata/stream.internal.conf, dest: /etc/netdata/stream.conf }
    - { src: user/mortis-configs/templates/mirrorlist.archlinux-arm, dest: /etc/pacman.d/mirrorlist }
