# enable tmux support
use_tmux: true

# additional users to create/setup
extra_users:
- { user: node-red, configure: false }

# Install list of arbitary packages
# set to empty to not install any
extra_packages:
  - netdata
  - nfs-utils
  - home-assistant
  # rabbitmq-plugins enable rabbitmq_mqtt
  - rabbitmq
  - npm
  - rsync

# Set to '[]' to skip installing AUR packages
extra_aur_packages:
  - nodejs-node-red
  # gpg --recv-keys 06CA9F5D1DCF2659
  - bluez-utils-compat

# Extra systemd services to enable
# Set to '[]' to skip
extra_systemd:
  - netdata.service
  - home-assistant.service
  - bluetooth.service
  - rabbitmq.service
  - node-red.service

# extra arbitary system files to copy
# set to '[]' to not copy any
extra_system_files:
  - { src: user/mortis-configs/templates/netdata/apps_groups.conf, dest: /etc/netdata/apps_groups.conf }
  - { src: user/mortis-configs/templates/netdata/netdata.pi-3.conf, dest: /etc/netdata/netdata.conf }
  - { src: user/mortis-configs/templates/netdata/python.d.conf, dest: /etc/netdata/python.d.conf }
  - { src: user/mortis-configs/templates/sysctl.conf, dest: /etc/sysctl.d/90-extra-tuning.conf }
  - { src: user/mortis-configs/templates/netdata/stream.internal.conf, dest: /etc/netdata/stream.conf }
  - { src: user/mortis-configs/templates/mirrorlist.manjaro-arm, dest: /etc/pacman.d/mirrorlist }
  - { src: user/mortis-configs/templates/rabbitmq/enabled_plugins, dest: /etc/rabbitmq/enabled_plugins }
  - { src: user/mortis-configs/templates/rabbitmq/rabbitmq.conf, dest: /etc/rabbitmq/rabbitmq.conf }
  - { src: user/mortis-configs/templates/rabbitmq/rabbitmq-env.conf, dest: /etc/rabbitmq/rabbitmq-env.conf }
  - { src: user/mortis-configs/templates/node-red.service, dest: /etc/systemd/system/node-red.service }

# extra drives to mount
# set to '[]' to not mount anything
extra_mounts:
  - { path: /unraid/backup, src: unraid-server.wl.mort.is:/mnt/user/backup, fstype: nfs, opts: defaults,timeo=900,retrans=5,_netdev }
  - { path: /unraid/public, src: unraid-server.wl.mort.is:/mnt/user/public, fstype: nfs, opts: defaults,timeo=900,retrans=5,_netdev }
  - { path: /etc/letsencrypt, src: pi-2.wl.mort.is:/etc/letsencrypt, fstype: nfs, opts: defaults,timeo=900,retrans=5,_netdev }


# Crons to set up
# set to '[]' to skip
extra_crons:
- name: 'home assistant backup'
  minute: "0"
  hour: "*/2"
  job: "rsync -av --delete /var/lib/hass/ /unraid/backup/hass/"
  user: hass
