# Set to '[]' to skip installing AUR packages
extra_aur_packages:
  - pacoloco-git

# Extra systemd services to enable
# Set to '[]' to skip
extra_systemd:
  - ssd1306.service
  # extra
  - pacoloco.service

# Install and set up NFS Network Shares
setup_nfs: true

# extra arbitary system directories to create
# set to '[]' to not copy any
extra_system_dirs:
  - { path: /opt/pacoloco/, owner: pacoloco, recurse: false, mode: '755' }

# extra arbitary system files to copy
# set to '[]' to not copy any
extra_system_files:
  - { src: user/mortis-configs/templates/mirrorlist.archlinux-arm, dest: /etc/pacman.d/mirrorlist }
  - { src: user/mortis-configs/templates/ssd1306.service, dest: /etc/systemd/system/ssd1306.service }
  # extra
  - { src: user/mortis-configs/templates/pacoloco.yml, dest: /etc/pacoloco.yaml }

# extra drives to mount
# set to '[]' to not mount anything
extra_mounts:
  - { path: /unraid/backup, src: unraid-server.wl.mort.is:/mnt/user/backup, fstype: nfs, opts: defaults,timeo=900,retrans=5,_netdev }
  - { path: /unraid/public, src: unraid-server.wl.mort.is:/mnt/user/public, fstype: nfs, opts: defaults,timeo=900,retrans=5,_netdev }
  - { path: /unraid/appdata, src: unraid-server.wl.mort.is:/mnt/user/appdata, fstype: nfs, opts: defaults,timeo=900,retrans=5,_netdev }


## nginx/Let's Encrypt

# email to use for Let's Encrypt certs
# set to empty to not config nginx/Let's encrypt
letencrypt_email: cbailey@mort.is

# domains to get SSL certs for
# set to '[]' to not config nginx/Let's encrypt
letencrypt_domains:
  - "wl.mort.is"
  - "*.wl.mort.is"

# nginx proxies to set up
# set to '[]' to not config nginx reverse proxies
nginx_proxies:
# server-2
- { domain: 'docker.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '9000', protocol: http, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'collect.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '19999', protocol: https, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, proto_header: http, group: "core" }
- { domain: 'influxdb.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '8086', protocol: http, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'monitor.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '3000', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'prometheus.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '9090', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'nodered.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '1880', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'paperless.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '8010', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'money.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '8444', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'spectre.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '8445', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'plaid-dev.wl.mort.is', ip: 'server-2-f1.wl.mort.is', port: '8455', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }

# unraid
- { domain: 'backup.wl.mort.is', ip: 'unraid-server.wl.mort.is', port: '7810', protocol: https, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "media" }
- { domain: 'movies.wl.mort.is', ip: 'unraid-server.wl.mort.is', port: '7878', protocol: http, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "media" }
- { domain: 'music.wl.mort.is', ip: 'unraid-server.wl.mort.is', port: '8686', protocol: http, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "media" }
- { domain: 'sync.wl.mort.is', ip: 'unraid-server.wl.mort.is', port: '8384', protocol: https, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "media" }
- { domain: 'television.wl.mort.is', ip: 'unraid-server.wl.mort.is', port: '8989', protocol: http, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "media" }
- { domain: 'unraid.wl.mort.is', ip: 'unraid-server.wl.mort.is', port: '7443', protocol: https, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }

# other
- { domain: 'unifi.wl.mort.is', ip: '192.168.1.1', port: '443', protocol: https, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'network.wl.mort.is', ip: '192.168.1.1', port: '443', protocol: https, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'protect.wl.mort.is', ip: '192.168.51.16', port: '443', protocol: https, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
- { domain: 'power.wl.mort.is', ip: 'iotawatt.wl.mort.is', port: '80', protocol: http, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: true, stats_ip: null, group: "core" }
