# additional users to create/setup
extra_users:
  - { user: cgolden, configure: false, groups: ["sftponly"] }
  - { user: jailtest, configure: false, groups: ["sftponly"] }

# Install list of arbitary packages
# set to empty to not install any
extra_packages:
  - nfs-utils
  - i2c-tools
  # extra
  - fail2ban

# Extra systemd services to enable
# Set to '[]' to skip
extra_systemd:
  - ssd1306.service
  # extra
  - fail2ban.service

# Install and set up NFS Network Shares
setup_nfs: true

# extra arbitary system directories to create
# set to '[]' to not copy any
extra_system_dirs:
  - { path: /unraid/media, owner: root, recurse: false, mode: '777' }
  - { path: /srv/ssh/jail/media, owner: root, recurse: false, mode: '755' }
  - { path: /srv/ssh/jail/media/music, owner: root, recurse: false, mode: '755' }
  - { path: /srv/ssh/jail/media/movies, owner: root, recurse: false, mode: '755' }
  - { path: /srv/ssh/jail/media/television, owner: root, recurse: false, mode: '755' }

# extra arbitary system files to copy
# set to '[]' to not copy any
extra_system_files:
  - { src: user/mortis-configs/templates/ssd1306.service, dest: /etc/systemd/system/ssd1306.service }
  # extra
  - { src: user/mortis-configs/authorized_keys, dest: /etc/ssh/authorized_keys/jailtest }
  - { src: user/mortis-configs/ssh-jail/cgolden.pub, dest: /etc/ssh/authorized_keys/cgolden }
  - { src: user/mortis-configs/jail.local, dest: /etc/fail2ban/jail.local }

# extra drives to mount
# set to '[]' to not mount anything
extra_mounts:
  - { path: /unraid/media, src: unraid-media.wl.mort.is:/mnt/user/media, fstype: nfs, opts: defaults,timeo=900,retrans=5,_netdev }
  - { path: /mnt/boundlexx, src: server-2.wl.mort.is:/media/docker/data/boundlexx/live/web, fstype: nfs, opts: defaults,timeo=900,retrans=5,_netdev }
  - { path: /srv/ssh/jail/media/music, src: /unraid/media/music, fstype: none, opts: bind,remount,ro }
  - { path: /srv/ssh/jail/media/movies, src: /unraid/media/movies, fstype: none, opts: bind,remount,ro }
  - { path: /srv/ssh/jail/media/television, src: /unraid/media/television, fstype: none, opts: bind,remount,ro }


## nginx/Let's Encrypt

# email to use for Let's Encrypt certs
# set to empty to not config nginx/Let's encrypt
letencrypt_email: cbailey@mort.is

# domains to get SSL certs for
# set to '[]' to not config nginx/Let's encrypt
letencrypt_domains:
  - "wl.mort.is"
  - "*.wl.mort.is"

# nginx proxies to set up
# set to '[]' to not config nginx reverse proxies
nginx_proxies:
# server-2
- { domain: 'wl.mort.is', ip: '192.168.2.12', port: '8123', protocol: http, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: false, stats_ip: null, websockets: false, group: "media", path: "~* /api/(webhook|camera_proxy|ufp)/" }

- { domain: 'media.wl.mort.is', ip: 'server-2.wl.mort.is', port: '3579', protocol: http, type: 'proxy', cors: true, cors_domain: 'mort.is', media_root: null, static_root: null, internal: false, stats_ip: null, websockets: false, group: "media" }
- { domain: 'plex.wl.mort.is', ip: 'unraid-media.wl.mort.is', port: '32400', protocol: https, type: 'proxy', cors: false, media_root: null, static_root: null, internal: false, stats_ip: null, group: "media" }
- { domain: 'jellyfin.wl.mort.is', ip: 'server-2.wl.mort.is', port: '8096', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: false, stats_ip: null, group: "media" }

# boundlexx
- { domain: 'local-boundlexx.wl.mort.is', custom: true, custom_file: user/mortis-configs/templates/nginx/local-boundlexx.wl.mort.is.conf, group: "boundlexx", env: "local" }
- { domain: 'testing-boundlexx.wl.mort.is', custom: true, custom_file: user/mortis-configs/templates/nginx/testing-boundlexx.wl.mort.is.conf, group: "boundlexx", env: "testing" }

- { domain: 'boundlexx.wl.mort.is', custom: true, custom_file: user/mortis-configs/templates/nginx/boundlexx.wl.mort.is.conf, group: "boundlexx" }
- { domain: 'boundlexx.app', ip: 'server-2.wl.mort.is', type: 'uwsgi', socket: 'server-2.wl.mort.is:12000', cors: false, media_root: null, static_root: '/mnt/boundlexx/static', internal: false, stats_ip: null, group: "boundlexx" }
- { domain: 'origin.boundlexx.app', ip: 'server-2.wl.mort.is', type: 'uwsgi', socket: 'server-2.wl.mort.is:12000', cors: false, media_root: null, static_root: '/mnt/boundlexx/static', internal: false, stats_ip: null, group: "boundlexx" }
- { domain: 'metabase.boundlexx.app', ip: 'server-2-f1.wl.mort.is', port: '12100', protocol: http, type: 'proxy', cors: false, media_root: null, static_root: null, internal: false, stats_ip: null, group: "boundlexx" }

## SSH jail
install_ssh_jail: true
ssh_jail_binaries:
  - /bin/awk
  - /bin/bash
  - /bin/cut
  - /bin/df
  - /bin/du
  - /bin/echo
  - /bin/env
  - /bin/false
  - /bin/head
  - /bin/ls
  - /bin/pwd
  - /bin/sed
  - /bin/seq
  - /bin/sleep
  - /bin/sort
  - /bin/tail
  - /bin/test
  - /bin/tr
  - /bin/true
  - /bin/uniq
  - /bin/wc
  - /bin/whoami
  - /bin/rsync
