# additional users to create/setup
extra_users:
  - { user: room-assistant, configure: false }

# Install list of arbitary packages
# set to empty to not install any
extra_packages:
  - netdata
  - nfs-utils
  - bluez
  - avahi
  - nss-mdns

# Set to '[]' to skip installing AUR packages
extra_aur_packages:
  # gpg --recv-keys 06CA9F5D1DCF2659
  - bluez-utils-compat

# extra arbitary system directories to create
# set to '[]' to not copy any
extra_system_dirs:
  - { path: /home/room-assistant/config, owner: room-assistant, recurse: false, mode: '755' }


# Extra systemd services to enable
# Set to '[]' to skip
extra_systemd:
  - netdata.service
  - bluetooth.service
  - room-assistant.service
  - avahi-daemon.service

# extra arbitary system files to copy
# set to '[]' to not copy any
extra_system_files:
  - { src: user/mortis-configs/templates/netdata/apps_groups.conf, dest: /etc/netdata/apps_groups.conf }
  - { src: user/mortis-configs/templates/netdata/netdata.pi-6.conf, dest: /etc/netdata/netdata.conf }
  - { src: user/mortis-configs/templates/netdata/python.d.conf, dest: /etc/netdata/python.d.conf }
  - { src: user/mortis-configs/templates/sysctl.conf, dest: /etc/sysctl.d/90-extra-tuning.conf }
  - { src: user/mortis-configs/templates/netdata/stream.internal.conf, dest: /etc/netdata/stream.conf }
  - { src: user/mortis-configs/templates/mirrorlist.archlinux-arm, dest: /etc/pacman.d/mirrorlist }
  - { src: user/mortis-configs/templates/room-assistant/pi-6.yml, dest: /home/room-assistant/config/local.yml }
  - { src: user/mortis-configs/templates/room-assistant.service, dest: /etc/systemd/system/room-assistant.service }
  - { src: user/mortis-configs/templates/room-assistant/nsswitch.conf, dest: /etc/nsswitch.conf }

## NodeJS/NPM
# Extra NPM packages to install
# set to '[]' to skip
extra_npm:
  - room-assistant

# extra drives to mount
# set to '[]' to not mount anything
extra_mounts: []
