#!/bin/sh

xset +dpms
xset s 60 60

unclutter &
chromium --app=https://home.wl.mort.is/lovelace/entertainment-room/ \
    --window-size=800,480 --start-fullscreen --kiosk \
    --noerrdialogs --disable-translate --no-first-run \
    --fast --fast-start --disable-infobars --disable-features=TranslateUI \
    --password-store=basic
