#!/bin/sh

xset +dpms
xset s 60 60

URL=https://home.wl.mort.is/lovelace/downstairs/

unclutter &
chromium $URL --app=$URL \
    --window-size=800,480 --start-fullscreen --kiosk \
    --noerrdialogs --disable-translate --no-first-run \
    --fast --fast-start --disable-infobars --disable-features=TranslateUI \
    --password-store=basic
